# Generated by Django 3.1 on 2020-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20200805_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find',
            old_name='dateFound',
            new_name='date_found',
        ),
        migrations.AddField(
            model_name='find',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
